function report=qn_local_worker_test()
% Regression test for one complete local-cover worker task.

outdir=tempname;
mkdir(outdir);
cleanup=onCleanup(@() rmdir(outdir,'s')); %#ok<NASGU>
qn_local_certificate_cover(20,13824,12,outdir);
T=readtable(fullfile(outdir,'res_020.csv'));
assert(height(T)==1 && T.box_id==20 && T.ok==1, ...
    'The representative worker box was not certified.');
assert(T.mass_matrix_lower>0 && T.lambda3_lower>16 && ...
    T.lambda3_minus_3pi2_over2_lower>0, ...
    'The worker box lacks the mass or index-3 veigs certificate.');
assert(isfile(fullfile(outdir,'done_020.txt')), ...
    'The local worker did not reach its completion marker.');
report=struct('box_id',T.box_id,'infS',T.inf_S, ...
    'depth',T.max_subdivision_depth,'mass_lower',T.mass_matrix_lower, ...
    'lambda3_lower',T.lambda3_lower);
fprintf('LOCAL WORKER OK: box=%d S=%.17g depth=%d mass>=%.17g lambda3>=%.17g\n', ...
    report.box_id,report.infS,report.depth,report.mass_lower,report.lambda3_lower);
end
