function report=qn_local_subdivision_test()
% Regression test for mixed S-only and veigs-undecided radial levels.

outdir=tempname;
mkdir(outdir);
cleanup=onCleanup(@() rmdir(outdir,'s')); %#ok<NASGU>
qn_local_certificate_cover(20,13824,12,outdir);
T=readtable(fullfile(outdir,'res_020.csv'));
assert(height(T)==1 && T.box_id==20 && T.ok==1, ...
    'The representative mixed-level box was not certified.');
assert(T.max_subdivision_depth>=1, ...
    'The regression box did not exercise local subdivision.');
assert(T.mass_matrix_lower>0 && T.lambda3_lower>16 && ...
    T.lambda3_minus_3pi2_over2_lower>0, ...
    'The regression box lacks the mass or index-3 veigs certificate.');
assert(isfile(fullfile(outdir,'done_020.txt')), ...
    'The local worker did not reach its completion marker.');
report=struct('box_id',T.box_id,'infS',T.inf_S, ...
    'subdivision_depth',T.max_subdivision_depth, ...
    'mass_lower',T.mass_matrix_lower,'lambda3_lower',T.lambda3_lower);
fprintf('LOCAL SUBDIVISION OK: box=%d S=%.17g depth=%d mass>=%.17g lambda3>=%.17g\n', ...
    report.box_id,report.infS,report.subdivision_depth, ...
    report.mass_lower,report.lambda3_lower);
end
