function report = qn_local_rigour_test(repo_root)
% Focused regression test for the local DQ2 proof path.
% Requires MATLAB and INTLAB; it does not run the full S^3 cover.

if nargin<1, repo_root=fileparts(fileparts(mfilename('fullpath'))); end
addpath(fullfile(repo_root,'src'));

PI=intval('pi');
rho=intval(3232)/(intval(27)*PI^6);
face_box=[1 1 -0.01 0.01 -0.01 0.01 -0.01 0.01];
[res,rem]=qn_single_box_certificate(face_box,1,[intval(0),rho]);

assert(all(isfinite(rem.BK(:))) && all(rem.BK(:)>=0), ...
    'Stiffness Taylor remainder radii are invalid.');
assert(all(isfinite(rem.BM(:))) && all(rem.BM(:)>=0), ...
    'Mass Taylor remainder radii are invalid.');
assert(all(isfinite(rem.Bb(:))) && all(rem.Bb(:)>=0), ...
    'Mean-vector Taylor remainder radii are invalid.');
assert(res(1).ok,'Representative local DQ2 box was not certified.');
assert(res(1).coarse_infS>0, ...
    'Representative box fails even before the exact root refinement.');
assert(res(1).infS>=res(1).coarse_infS, ...
    'Exact root-identity intersection unexpectedly weakened the S bound.');
assert(res(1).root_identity_used, ...
    'Exact root-identity refinement was not exercised by the test.');
assert(res(1).veigs_verified && any(res(1).veigs_indices==1) && ...
    any(res(1).veigs_indices==3), ...
    'Representative local DQ2 box was not certified by veigs for indices 1 and 3.');
assert(res(1).mass_lower>0, ...
    'Representative local DQ2 box has no positive Gershgorin mass bound.');
assert(res(1).veigs_lambda3(1)>16 && res(1).lambda3_gap_lower>0, ...
    'Representative local DQ2 box does not certify lambda_3>16.');

report=struct('ok',res(1).ok,'infS',res(1).infS, ...
    'coarse_infS',res(1).coarse_infS, ...
    'root_identity_gain',res(1).root_identity_gain, ...
    'max_BK',max(rem.BK(:)),'max_BM',max(rem.BM(:)), ...
    'max_Bb',max(rem.Bb(:)),'veigs_lambda1',res(1).veigs_lambda1, ...
    'veigs_lambda3',res(1).veigs_lambda3,'mass_lower',res(1).mass_lower, ...
    'lambda3_gap_lower',res(1).lambda3_gap_lower, ...
    'veigs_indices',res(1).veigs_indices);
fprintf(['LOCAL RIGOUR OK: coarse S=%.17g refined S=%.17g gain=%.17g ' ...
    'mass>=%.17g lambda3>=%.17g\n'],report.coarse_infS,report.infS, ...
    report.root_identity_gain,report.mass_lower,report.veigs_lambda3(1));
end
