function report = qn_smoke_test(repo_root)
% Quick integration check; requires MATLAB and INTLAB but no full recomputation.

if nargin<1, repo_root=fileparts(fileparts(mfilename('fullpath'))); end
addpath(fullfile(repo_root,'src'));
C=qn_global_constants();
assert(in(3232/(27*pi^6),C.rho_sharp));
runtimeProvenance=qn_runtime_provenance();
assert(~runtimeProvenance.source_dirty && ...
    strcmp(runtimeProvenance.veigs_commit, ...
    '6556d39a0d9819bb172d232062b698aa76e420f6') && ...
    ~isempty(regexp(runtimeProvenance.intlab_start_sha256, ...
    '^[0-9a-f]{64}$','once')) && ...
    ~isempty(regexp(runtimeProvenance.intlab_tree_sha256, ...
    '^[0-9a-f]{64}$','once')), ...
    'Runtime provenance does not bind a clean source and pinned dependencies.');

% The D_4 action preceding (13): one representative per initial-grid orbit.
initialBoxes=qn_initial_cover(3); retainedInitial=0; retainedInitialIds=[];
canonicalGridIndices=zeros(0,4);
for boxIndex=1:numel(initialBoxes)
    orbit=unique(round(qn_d4_images(initialBoxes{boxIndex}.center).'*1e12),'rows');
    canonicalInOrbit=0;
    for imageIndex=1:size(orbit,1)
        canonicalInOrbit=canonicalInOrbit+ ...
            qn_d4_is_canonical(orbit(imageIndex,:).'/1e12);
    end
    assert(canonicalInOrbit==1, ...
        'The D_4 rule does not select exactly one representative of an orbit.');
    if qn_d4_is_canonical(initialBoxes{boxIndex}.center)
        indexRemainder=boxIndex-1;
        i4=mod(indexRemainder,3)+1; indexRemainder=floor(indexRemainder/3);
        i3=mod(indexRemainder,3)+1; indexRemainder=floor(indexRemainder/3);
        i2=mod(indexRemainder,3)+1; indexRemainder=floor(indexRemainder/3);
        i1=indexRemainder+1;
        canonicalGridIndices(end+1,:)=[i1 i2 i3 i4]; %#ok<AGROW>
    end
    if qn_d4_is_canonical(initialBoxes{boxIndex}.center) && ...
            ~qn_box_outside_pk(initialBoxes{boxIndex}.center, ...
            initialBoxes{boxIndex}.half_widths)
        retainedInitial=retainedInitial+1;
        retainedInitialIds(end+1,1)=initialBoxes{boxIndex}.initial_id; %#ok<AGROW>
    end
end
expectedCanonicalGridIndices=[ ...
    2 2 2 2; 2 2 2 3; 2 3 2 2; 2 3 2 3; ...
    2 3 3 1; 2 3 3 2; 2 3 3 3; 3 2 2 2; ...
    3 2 2 3; 3 2 3 2; 3 2 3 3; 3 3 2 2; ...
    3 3 2 3; 3 3 3 1; 3 3 3 2; 3 3 3 3];
assert(isequal(canonicalGridIndices,expectedCanonicalGridIndices), ...
    'The canonical initial-grid representatives differ from the D_4 action.');
assert(retainedInitial==16, ...
    'The corrected D_4 reduction does not retain the expected 16 initial boxes.');

% This point lies in the orbit omitted by the older 18-box rule.
omittedByOldRule=[0;0.28;0.28;-0.03];
assert(~qn_box_outside_pk(omittedByOldRule,zeros(4,1)) && ...
    norm(omittedByOldRule)>sup(C.rho_sharp_over_2), ...
    'The D_4 regression point is not in the required global region.');
coveredByCurrentRule=false;
for boxIndex=1:numel(initialBoxes)
    if qn_d4_is_canonical(initialBoxes{boxIndex}.center) && ...
            all(in(omittedByOldRule,qn_interval_box( ...
            initialBoxes{boxIndex}.center,initialBoxes{boxIndex}.half_widths)))
        coveredByCurrentRule=true;
        break
    end
end
assert(coveredByCurrentRule, ...
    'The corrected D_4 representatives do not cover the regression point.');
assert(qn_box_inside_ball(zeros(4,1),zeros(4,1),C.rho_sharp_over_2), ...
    'The first discard condition in (46) failed at the origin.');
justOutsideBall=[sup(C.rho_sharp_over_2)+1e-6;0;0;0];
assert(~qn_box_inside_ball(justOutsideBall,zeros(4,1),C.rho_sharp_over_2), ...
    'A point outside the ball was discarded by the first condition in (46).');
assert(~qn_box_outside_pk(zeros(4,1),zeros(4,1)), ...
    'The square was discarded by a P_K condition in (46).');
assert(qn_box_outside_pk([2;0;0;0],zeros(4,1)), ...
    'The P_K discard conditions in (46) failed on an exterior point.');

[K0,M0,q0]=qn_km_enclosure(zeros(4,1),zeros(4,1));
PI=intval('pi');
Kexact=diag([PI^2/intval('2'),PI^2/intval('2'),PI^2/intval('2'), ...
    intval('2')*PI^2,intval('2')*PI^2]);
Mexact=diag([intval('0.5'),intval('0.5'),intval('0.25'),intval('0.5'),intval('0.5')]);
assert(all(all(in(mid(Kexact),K0))) && all(all(in(mid(Mexact),M0))) && in(1,q0), ...
    'Square pencil enclosure misses its analytic value.');
center=[0.10;0.05;0.04;0.02]; hw=[0.01;0.004;0.003;0.002];
[~,M,q_box]=qn_km_enclosure(center,hw);
interiorValid=qn_interval_ldl_pd(M) && inf(q_box)>0;
assert(interiorValid,'Representative pencil is not certifiably regular.');
[verdict,info,sdim]=qn_certify_box(center,hw);
assert(strcmp(verdict,'cert') && strcmp(info.route,'veigs') && ...
    any(info.index_range==1),'Representative box was not certified by veigs.');
assert(info.q_lower>0 && info.mass_pd && info.lambda1(1)>0 && ...
    info.delta_lower>0 && info.margin==info.delta_lower, ...
    'Representative box does not satisfy every condition in (44).');

% Direct rejection tests for the five conditions in (44).
[accepted,reason]=qn_global_code_test(intval('-1'),true, ...
    intval('1'),1,C.pi2);
assert(~accepted && strcmp(reason,'q_not_positive'), ...
    'A nonpositive lower q was not rejected by (44).');
[accepted,reason]=qn_global_code_test(intval('1'),false, ...
    intval('1'),1,C.pi2);
assert(~accepted && strcmp(reason,'mass_not_pd'), ...
    'Failure of mass-matrix positivity was not rejected by (44).');
[accepted,reason]=qn_global_code_test(intval('1'),true, ...
    intval('1'),2,C.pi2);
assert(~accepted && strcmp(reason,'index_1_not_verified'), ...
    'Missing verified index 1 was not rejected by (44).');
[accepted,reason]=qn_global_code_test(intval('1'),true, ...
    infsup(-1,1),1,C.pi2);
assert(~accepted && strcmp(reason,'lambda1_not_positive'), ...
    'A nonpositive lower eigenvalue was not rejected by (44).');
[accepted,reason]=qn_global_code_test(intval('1'),true, ...
    intval('20'),1,C.pi2);
assert(~accepted && strcmp(reason,'delta_not_positive'), ...
    'A nonpositive Delta_B was not rejected by (44).');
assert(hw(sdim)>=max(hw)/2, ...
    'The subdivision coordinate does not satisfy the condition before (47).');

% Rounding-sensitive regression for the covering relation in (47).
parent=struct('center',[-0.5482156771613484;-0.2;0.3;-0.4], ...
    'half_widths',[0.274107838580676;0.04;0.02;0.01],'depth',3);
[leftChild,rightChild]=qn_bisect_box(parent,1);
parentBox=qn_interval_box(parent.center,parent.half_widths);
leftBox=qn_interval_box(leftChild.center,leftChild.half_widths);
rightBox=qn_interval_box(rightChild.center,rightChild.half_widths);
childHull=hull(leftBox,rightBox);
assert(all(in(parentBox,childHull)), ...
    'The two children do not cover their parent in (47).');
assert(sup(leftBox(1))>=inf(rightBox(1)), ...
    'The two children have a gap in the bisected coordinate.');
assert(leftChild.half_widths(1)<parent.half_widths(1) && ...
    rightChild.half_widths(1)<parent.half_widths(1), ...
    'Bisection in (47) did not reduce the selected half-width.');

% Direct regression for the two correction formulas in (39).
[LCorrection,productCorrection]=qn_exact_root_refinement_corrections( ...
    intval('-2'),intval('3'),intval('0.5'),intval('-0.25'),intval('0.25'));
assert(in(0.25,LCorrection) && in(0.4921875,productCorrection), ...
    'The exact refinement corrections do not agree with (39).');

% The first condition in (44) must reject a box with nonpositive q.
[qVerdict,qInfo]=qn_certify_box([1;0;0;0],zeros(4,1));
assert(strcmp(qVerdict,'fail') && strcmp(qInfo.reason,'q_not_positive'), ...
    'A box with nonpositive lower q was not rejected.');

% A box crossing a genuine triangle face c_3=0 must be assemblable. The
% physical-gradient stiffness formula has no division by J, even though the
% reference-map Jacobian interval contains zero at the degenerate corner.
a=-0.17123475299635676; b=0.20062825348897717; d=-0.022264254417977088;
c=(1-a*a-d*d-b*(1-d+a))/(1-d-a);
boundaryCenter=[a;b;c;d]; boundaryHw=1e-6*ones(4,1);
pb=qn_interval_box(boundaryCenter,boundaryHw);
c3=intval('1')-pb(1)^2-pb(4)^2-(pb(2)+pb(3))*(intval('1')-pb(4)) ...
    -pb(1)*(pb(2)-pb(3));
assert(inf(c3)<=0 && sup(c3)>=0,'Boundary smoke box does not cross c_3=0.');
assert(~qn_box_outside_pk(boundaryCenter,boundaryHw), ...
    'A box crossing c_3=0 was incorrectly discarded by (46).');
[~,Mb,qBoundary]=qn_km_enclosure(boundaryCenter,boundaryHw);
boundaryValid=qn_interval_ldl_pd(Mb) && inf(qBoundary)>0;
assert(boundaryValid,'Triangle-boundary pencil is not certifiably regular.');
[boundaryVerdict,boundaryInfo]=qn_certify_box(boundaryCenter,boundaryHw);
assert(strcmp(boundaryVerdict,'cert'), ...
    'Representative triangle-boundary box was not certified.');
assert(strcmp(boundaryInfo.route,'veigs') && any(boundaryInfo.index_range==1), ...
    'Triangle-boundary box was not certified by veigs with index 1.');

localWorker=qn_local_worker_test();
local=qn_summarize_local_results(fullfile(repo_root,'results','local'),60,12);
if local.current_provenance_present
    assert(local.verified, ...
        'The saved current-schema local run is incomplete or mismatched.');
else
    assert(local.certificate_bounds_verified && ~local.verified, ...
        'The earlier saved local run is incomplete or was marked current.');
end

% The saved-result verifier must reject a truncated ID prefix and must use
% the caller's expected worker count rather than the files that happen to exist.
localVerifierDir=tempname; mkdir(localVerifierDir);
localVerifierCleanup=onCleanup(@() rmdir(localVerifierDir,'s')); %#ok<NASGU>
localResultPath=fullfile(localVerifierDir,'res_001.csv');
write_local_results(localResultPath,1);
write_done_marker(fullfile(localVerifierDir,'done_001.txt'));
truncatedLocal=qn_summarize_local_results(localVerifierDir,1,1);
assert(~truncatedLocal.id_coverage_complete && ~truncatedLocal.verified, ...
    'A truncated prefix of local box IDs was accepted as a complete cover.');
write_local_results(localResultPath,1:8);
missingWorkerLocal=qn_summarize_local_results(localVerifierDir,2,1);
assert(missingWorkerLocal.id_coverage_complete && ...
    ~missingWorkerLocal.done_markers_complete && ~missingWorkerLocal.verified, ...
    'A local cover with a missing expected worker/DONE marker was accepted.');

savedMergeOutput=[tempname '.json'];
savedMergeCleanup=onCleanup(@() delete(savedMergeOutput)); %#ok<NASGU>
savedGlobal=qn_merge_global_results( ...
    fullfile(repo_root,'results','global'),16,savedMergeOutput);
assert(savedGlobal.complete && savedGlobal.current_schema_present && ...
    savedGlobal.current_provenance_valid && ...
    savedGlobal.current_worker_bounds_valid && ...
    savedGlobal.current_initial_assignment_valid, ...
    'The saved current-schema global run is incomplete or mismatched.');

% A completed legacy aggregate is evidence only for the earlier schema; it
% must not be promoted to a current (44)--(48) certificate.
legacyMergeDir=tempname; mkdir(legacyMergeDir);
legacyMergeCleanup=onCleanup(@() rmdir(legacyMergeDir,'s')); %#ok<NASGU>
legacyWorker=struct('verified',retainedInitial,'discarded',0,'bisected',0, ...
    'unverified',0,'veigs_certified',retainedInitial,'max_depth',0, ...
    'min_certified_margin',0.1,'min_margin_at',zeros(1,4), ...
    'wall_seconds',1,'n_init',3,'initial_retained',retainedInitial, ...
    'initial_retained_all',retainedInitial,'worker_id',1,'worker_count',1, ...
    'rho_seam',mid(C.rho_sharp_over_2),'complete',true);
write_json(fullfile(legacyMergeDir,'worker_001.json'),legacyWorker);
legacyGlobal=qn_merge_global_results(legacyMergeDir,1, ...
    fullfile(legacyMergeDir,'summary.json'));
assert(legacyGlobal.legacy_completion_recorded && ...
    ~legacyGlobal.current_schema_present && ~legacyGlobal.complete, ...
    'Old global output was misclassified as a current (44)--(48) certificate.');

% Current-schema merge accepts complete records and rejects a missing bound.
currentMergeDir=tempname; mkdir(currentMergeDir);
currentMergeCleanup=onCleanup(@() rmdir(currentMergeDir,'s')); %#ok<NASGU>
currentWorker=struct('verified',retainedInitial,'discarded',0,'bisected',0, ...
    'unverified',0,'veigs_certified',retainedInitial,'max_depth',0, ...
    'delta_star_lower',0.1,'delta_star_at',zeros(1,4), ...
    'q_lower_min',0.2,'lambda_lower_min',0.3,'wall_seconds',1, ...
    'n_init',3,'initial_retained',retainedInitial, ...
    'initial_retained_all',retainedInitial, ...
    'worker_id',1,'worker_count',1, ...
    'rho_sharp_over_2',mid(C.rho_sharp_over_2), ...
    'schema_version',3,'initial_box_ids',retainedInitialIds', ...
    'source_commit',runtimeProvenance.source_commit,'source_dirty',false, ...
    'source_code_sha256',runtimeProvenance.source_code_sha256, ...
    'veigs_commit','6556d39a0d9819bb172d232062b698aa76e420f6', ...
    'run_id','smoke-test','matlab_version',version, ...
    'matlab_release',version('-release'), ...
    'intlab_start_sha256',runtimeProvenance.intlab_start_sha256, ...
    'intlab_tree_sha256',runtimeProvenance.intlab_tree_sha256, ...
    'worker_complete',true,'complete',true);
currentWorkerPath=fullfile(currentMergeDir,'worker_001.json');
write_json(currentWorkerPath,currentWorker);
currentMerged=qn_merge_global_results(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-valid.json'));
assert(currentMerged.complete && currentMerged.current_provenance_valid && ...
    currentMerged.current_worker_bounds_valid && ...
    currentMerged.current_initial_assignment_valid && ...
    isequal(currentMerged.initial_box_ids,retainedInitialIds'), ...
    'A complete current-schema worker was not accepted by (48).');
currentWorker.rho_sharp_over_2=currentWorker.rho_sharp_over_2+0.01;
write_json(currentWorkerPath,currentWorker);
assert_merge_rejected(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-wrong-radius.json'),'required rho^sharp/2');
currentWorker.rho_sharp_over_2=mid(C.rho_sharp_over_2);
currentWorker.verified=retainedInitial-1;
currentWorker.veigs_certified=retainedInitial-1;
currentWorker.bisected=-1;
write_json(currentWorkerPath,currentWorker);
assert_merge_rejected(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-negative-count.json'),'finite nonnegative integer');
currentWorker.verified=retainedInitial;
currentWorker.veigs_certified=retainedInitial;
currentWorker.bisected=0;
currentWorker.source_dirty=true;
write_json(currentWorkerPath,currentWorker);
dirtySourceMerged=qn_merge_global_results(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-dirty-source.json'));
assert(~dirtySourceMerged.complete && ...
    ~dirtySourceMerged.current_provenance_valid, ...
    'A current worker from a dirty source tree was accepted.');
currentWorker.source_dirty=false;
currentWorker.source_code_sha256=repmat('c',1,64);
write_json(currentWorkerPath,currentWorker);
mismatchedSourceMerged=qn_merge_global_results(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-mismatched-source.json'));
assert(~mismatchedSourceMerged.complete && ...
    ~mismatchedSourceMerged.current_provenance_valid, ...
    'A worker from different executable source was accepted.');
currentWorker.source_code_sha256=runtimeProvenance.source_code_sha256;
wrongInitialId=setdiff((1:numel(initialBoxes))',retainedInitialIds);
currentWorker.initial_box_ids(1)=wrongInitialId(1);
write_json(currentWorkerPath,currentWorker);
wrongInitialMerged=qn_merge_global_results(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-wrong-initial-id.json'));
assert(~wrongInitialMerged.complete && ...
    ~wrongInitialMerged.current_initial_assignment_valid, ...
    'A current worker with the wrong D_4 initial-box set was accepted.');
currentWorker.initial_box_ids=retainedInitialIds';
currentWorker.q_lower_min=[];
write_json(currentWorkerPath,currentWorker);
invalidMerged=qn_merge_global_results(currentMergeDir,1, ...
    fullfile(currentMergeDir,'summary-invalid.json'));
assert(~invalidMerged.complete && ~invalidMerged.current_worker_bounds_valid, ...
    'A current worker with a missing (44) bound was accepted by (48).');
report=struct('constants',struct('rho_sharp',mid(C.rho_sharp), ...
    'rho_sharp_over_2',mid(C.rho_sharp_over_2)), ...
    'ok',true, ...
    'd4_initial_representatives',retainedInitial, ...
    'interior_pencil_regular',interiorValid, ...
    'nonpositive_q_rejected',true, ...
    'triangle_boundary_enclosure',struct('crosses_c3_zero',true, ...
        'regular',boundaryValid,'verdict',boundaryVerdict,'info',boundaryInfo), ...
    'sample_box',struct('verdict',verdict,'info',info,'split_dim',sdim), ...
    'local_worker',localWorker, ...
    'local_saved_results_verified',local.verified, ...
    'local_saved_results_legacy_verified',local.legacy_certificate_verified, ...
    'local_saved_results_table3_fields',local.table3_fields_present);
report.global_saved_results_current_schema= ...
    savedGlobal.current_schema_present;
report.global_saved_results_verified=savedGlobal.complete;
report.legacy_global_rejected_as_current=~legacyGlobal.complete;
if isfield(info,'reason'), detail=info.reason; else, detail=info.route; end
fprintf('SMOKE OK: interior=%d boundary=%d sample=%s (%s)\n', ...
    interiorValid,boundaryValid,verdict,detail);
end

function write_json(path,value)
fid=fopen(path,'w'); assert(fid>=0,'Cannot open temporary JSON file.');
cleanup=onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
end

function write_local_results(path,box_ids)
fid=fopen(path,'w'); assert(fid>=0,'Cannot open temporary local CSV file.');
cleanup=onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,['box_id,ok,inf_S,max_subdivision_depth,elapsed_seconds,' ...
    'lambda1_lower,lambda2_upper,mass_matrix_lower,lambda3_lower,' ...
    'lambda3_minus_3pi2_over2_lower\n']);
for box_id=box_ids
    fprintf(fid,'%d,1,1,0,0,1,2,1,17,1\n',box_id);
end
end

function write_done_marker(path)
fid=fopen(path,'w'); assert(fid>=0,'Cannot open temporary DONE file.');
cleanup=onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,'nfail=0\n');
end

function assert_merge_rejected(results_dir,worker_count,output_file,message_fragment)
rejected=false;
try
    qn_merge_global_results(results_dir,worker_count,output_file);
catch ME
    rejected=contains(ME.message,message_fragment);
end
assert(rejected,'Invalid global worker summaries were not rejected for: %s', ...
    message_fragment);
end
