function tf = qn_box_outside_pk(center,half_widths)
% Conservative certified discard predicate for P_K.

C=qn_global_constants(); p=qn_interval_box(center,half_widths);
a=p(1); b=p(2); c=p(3); d=p(4); one=intval('1'); two=intval('2');
base=one-a^2-d^2;
ci=[base+(b+c)*(one-d)+a*(b-c); ...
    base-(b-c)*(one+d)-a*(b+c); ...
    base-(b+c)*(one-d)-a*(b-c); ...
    base+(b-c)*(one+d)+a*(b+c)];
for k=1:4
    if sup(ci(k))+sup(C.ulp_pad)<0, tf=true; return; end
end
dist=[(one+b-a)^2+(c+d)^2; ...
      (one+a+c)^2+(b+d)^2; ...
      (one-a-b)^2+(c-d)^2; ...
      (one+a-c)^2+(b-d)^2; ...
      two*a^2+two*(one-d)^2; ...
      two*a^2+two*(one+d)^2];
for k=1:6
    if inf(dist(k))-sup(C.ulp_pad)>sup(C.T), tf=true; return; end
end
tf=false;
end
