function [CK,CM,Cb] = dq2_evaluate_taylor_coefficients_vectorized(TC,ea,eb,ec,ed)
% Vectorized evaluation of the exact symbolic local Taylor polynomials.
%
% The integer exponent table and certified coefficient matrices are unchanged.
% INTLAB evaluates the powers and elementwise products in the input class
% (intval or hessian), preserving outward rounding and derivative propagation.

E=TC.MEXP;
va=selected_powers(ea,E(:,1)); vb=selected_powers(eb,E(:,2));
vc=selected_powers(ec,E(:,3)); vd=selected_powers(ed,E(:,4));
monvals=va.*vb.*vc.*vd;
monvals=monvals(:);
CK=cell(10,1); CM=cell(10,1); Cb=cell(10,1);
for j=0:9
    vK=TC.CK{j+1}*monvals;
    vM=TC.CM{j+1}*monvals;
    vB=TC.Cb{j+1}*monvals;
    CK{j+1}=expand5(vK);
    CM{j+1}=expand5(vM);
    Cb{j+1}=vB;
end
end

function v=selected_powers(x,exponents)
% Avoid the undefined derivative generated by a generic hessian 0^0.  Build
% positive integer powers recursively and assign them by exponent group;
% exponent zero stays the exact constant one.
one=x*0+1; v=one.*ones(size(exponents)); power=one;
for k=1:max(exponents)
    power=power*x;
    idx=(exponents==k);
    if any(idx), v(idx)=power; end
end
end

function A=expand5(v)
A=[v(1) v(2) v(3) v(4) v(5); ...
   v(2) v(6) v(7) v(8) v(9); ...
   v(3) v(7) v(10) v(11) v(12); ...
   v(4) v(8) v(11) v(13) v(14); ...
   v(5) v(9) v(12) v(14) v(15)];
end
