function [L_correction,nu_product_correction] = ...
    qn_exact_root_refinement_corrections( ...
    nuhat1,nuhat2,delta1_over_t,delta2_over_t,t)
% Corrections in equation (39), with delta_i/t supplied continuously at t=0.

L_correction=delta1_over_t+delta2_over_t;
nu_product_correction= ...
    t*(nuhat1*delta2_over_t+nuhat2*delta1_over_t) + ...
    sqr(t)*delta1_over_t*delta2_over_t;
end
