function digest = qn_source_code_sha256(repo_root,revision)
% Hash committed Git tree entries that define the executable source.

if nargin<2 || isempty(revision), revision='HEAD'; end
assert(strcmp(revision,'HEAD') || ...
    ~isempty(regexp(revision,'^[0-9a-f]{40}$','once')), ...
    'Git revision must be HEAD or a full lowercase commit.');
assert(~contains(repo_root,''''), ...
    'Repository paths containing a single quote are unsupported.');
command=sprintf([ ...
    'git -C ''%s'' cat-file -e ''%s^{commit}'' && ' ...
    'git -C ''%s'' ls-tree -r --full-tree ''%s'' -- src scripts tests data ' ...
    '| LC_ALL=C sort | sha256sum'], ...
    repo_root,revision,repo_root,revision);
[status,output]=system(command);
token=regexp(strtrim(output),'^([0-9a-f]{64})\s','tokens','once');
assert(status==0 && ~isempty(token), ...
    'Cannot compute the certificate source-code digest.');
digest=token{1};
end
